name: portfolio_rodrigo_shira_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_neumorphic: ^3.2.0
  outline_gradient_button: ^2.0.1+1
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/ShiraLogoTipografia2-PNG-c2.png
    - lib/assets/GitHubIcon2 1.png
    - lib/assets/LinkedinIcon2 1.png
    - lib/assets/ShiraLogo - Home.png
    - lib/assets/4210456 2.png
    - lib/assets/ShiraLogo-PNG-C-3d(2)-(1) 43.png
    - lib/assets/Javascript_badge-c 1.png
    - lib/assets/Bootstrap_logo-c 1.png
    - lib/assets/CSS-logo-3 2.png
    - lib/assets/HTML-logo 2.png
    - lib/assets/MySQL_textlogo 1.png
    - lib/assets/Git-Icon-1788C-c 1.png
    - lib/assets/Python-logo-notext 1.png
    - lib/assets/WordPress_blue_logo-c 1.png
    - lib/assets/1667px-Figma-logo-c 1.png
    - lib/assets/Adobe_Photoshop_CC_icon-c 1.png
    - lib/assets/Flutter_logo.svg.png
    - lib/assets/Dart-logo.png
    - lib/assets/ShiraLogo-PNG-C-3d(2)-(1)2 12.png
    - lib/assets/unnamed 1.png
    - lib/assets/firebase_logo_icon_171157.png
    - lib/assets/fotoLinkedin2.png
    - lib/assets/shiraclimates.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  fonts:
  - family: Poppins
    fonts:
      - asset: lib/fonts/Poppins-Black.ttf
      - asset: lib/fonts/Poppins-BlackItalic.ttf
      - asset: lib/fonts/Poppins-Bold.ttf
      - asset: lib/fonts/Poppins-BoldItalic.ttf
      - asset: lib/fonts/Poppins-ExtraBold.ttf
      - asset: lib/fonts/Poppins-ExtraBoldItalic.ttf
      - asset: lib/fonts/Poppins-ExtraLight.ttf
      - asset: lib/fonts/Poppins-ExtraLightItalic.ttf
      - asset: lib/fonts/Poppins-Italic.ttf
      - asset: lib/fonts/Poppins-Light.ttf
      - asset: lib/fonts/Poppins-LightItalic.ttf
      - asset: lib/fonts/Poppins-Medium.ttf
      - asset: lib/fonts/Poppins-MediumItalic.ttf
      - asset: lib/fonts/Poppins-Regular.ttf
      - asset: lib/fonts/Poppins-SemiBold.ttf
      - asset: lib/fonts/Poppins-SemiBoldItalic.ttf
      - asset: lib/fonts/Poppins-Thin.ttf
      - asset: lib/fonts/Poppins-ThinItalic.ttf
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
